name: mixedcoord
channels:
  - conda-forge
dependencies:
  - python=3.9.9
  - ipython=8.0.0
  - matplotlib=3.5.1
  - numpy=1.22.0
  - pandas=1.3.5
  - patsy=0.5.2
  - scikit-image=0.19.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - statsmodels=0.13.1
  
